import "package:flutter/material.dart";

// Light and Dark Theme for Application
// Color Scheme generated by Figma
class AppTheme {
  static MaterialScheme lightScheme() {
    return const MaterialScheme(
      brightness: Brightness.light,
      primary: Color(0xfff38221),
      surfaceTint: Color(0xff8a5023),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xffffdcc6),
      onPrimaryContainer: Color(0xff311400),
      secondary: Color(0xff755846),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffffdcc6),
      onSecondaryContainer: Color(0xff2b1708),
      tertiary: Color(0xff5f6134),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xffe5e6ae),
      onTertiaryContainer: Color(0xff1c1d00),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff410002),
      background: Color(0xfffff8f5),
      onBackground: Color(0xff221a15),
      surface: Color(0xfffff8f5),
      onSurface: Color(0xff221a15),
      surfaceVariant: Color(0xfff4ded3),
      onSurfaceVariant: Color(0xff52443b),
      outline: Color(0xff84746a),
      outlineVariant: Color(0xffd7c3b7),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff382e29),
      inverseOnSurface: Color(0xfffeede4),
      inversePrimary: Color(0xffffb786),
      primaryFixed: Color(0xffffdcc6),
      onPrimaryFixed: Color(0xff311400),
      primaryFixedDim: Color(0xffffb786),
      onPrimaryFixedVariant: Color(0xff6e390d),
      secondaryFixed: Color(0xffffdcc6),
      onSecondaryFixed: Color(0xff2b1708),
      secondaryFixedDim: Color(0xffe4bfa8),
      onSecondaryFixedVariant: Color(0xff5b4130),
      tertiaryFixed: Color(0xffe5e6ae),
      onTertiaryFixed: Color(0xff1c1d00),
      tertiaryFixedDim: Color(0xffc9ca94),
      onTertiaryFixedVariant: Color(0xff47491f),
      surfaceDim: Color(0xffe7d7ce),
      surfaceBright: Color(0xfffff8f5),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfffff1ea),
      surfaceContainer: Color(0xfffcebe2),
      surfaceContainerHigh: Color(0xfff6e5dc),
      surfaceContainerHighest: Color(0xfff0dfd7),
    );
  }

  static ThemeData light() {
    return theme(lightScheme().toColorScheme());
  }

  static MaterialScheme darkScheme() {
    return const MaterialScheme(
      brightness: Brightness.dark,
      primary: Color(0xffffb786),
      surfaceTint: Color(0xffffb786),
      onPrimary: Color(0xff502400),
      primaryContainer: Color(0xff6e390d),
      onPrimaryContainer: Color(0xffffdcc6),
      secondary: Color(0xffe4bfa8),
      onSecondary: Color(0xff422b1b),
      secondaryContainer: Color(0xff5b4130),
      onSecondaryContainer: Color(0xffffdcc6),
      tertiary: Color(0xffc9ca94),
      onTertiary: Color(0xff31320a),
      tertiaryContainer: Color(0xff47491f),
      onTertiaryContainer: Color(0xffe5e6ae),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      background: Color(0xff19120d),
      onBackground: Color(0xfff0dfd7),
      surface: Color(0xff19120d),
      onSurface: Color(0xfff0dfd7),
      surfaceVariant: Color(0xff52443b),
      onSurfaceVariant: Color(0xffd7c3b7),
      outline: Color(0xff9f8d83),
      outlineVariant: Color(0xff52443b),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xfff0dfd7),
      inverseOnSurface: Color(0xff382e29),
      inversePrimary: Color(0xff8a5023),
      primaryFixed: Color(0xffffdcc6),
      onPrimaryFixed: Color(0xff311400),
      primaryFixedDim: Color(0xffffb786),
      onPrimaryFixedVariant: Color(0xff6e390d),
      secondaryFixed: Color(0xffffdcc6),
      onSecondaryFixed: Color(0xff2b1708),
      secondaryFixedDim: Color(0xffe4bfa8),
      onSecondaryFixedVariant: Color(0xff5b4130),
      tertiaryFixed: Color(0xffe5e6ae),
      onTertiaryFixed: Color(0xff1c1d00),
      tertiaryFixedDim: Color(0xffc9ca94),
      onTertiaryFixedVariant: Color(0xff47491f),
      surfaceDim: Color(0xff19120d),
      surfaceBright: Color(0xff413731),
      surfaceContainerLowest: Color(0xff140d08),
      surfaceContainerLow: Color(0xff221a15),
      surfaceContainer: Color(0xff261e19),
      surfaceContainerHigh: Color(0xff312823),
      surfaceContainerHighest: Color(0xff3d332d),
    );
  }

  static ThemeData dark() {
    return theme(darkScheme().toColorScheme());
  }

  static ThemeData theme(ColorScheme colorScheme) => ThemeData(
        useMaterial3: true,
        brightness: colorScheme.brightness,
        colorScheme: colorScheme,
        scaffoldBackgroundColor: colorScheme.background,
        canvasColor: colorScheme.surface,
      );
}

// Theme Util Helper class
class ThemeUtils {
  static ThemeData getTheme(BuildContext context) {
    return Theme.of(context);
  }

  static ColorScheme getColorScheme(BuildContext context) {
    return getTheme(context).colorScheme;
  }

  static bool isDarkMode(BuildContext context) {
    return getTheme(context).brightness == Brightness.dark;
  }

  static Color nvBackgroundColor(BuildContext context) {
    return isDarkMode(context)
        ? getTheme(context).colorScheme.surface
        : getTheme(context).colorScheme.primary;
  }

  static Color primContainerColor(BuildContext context) {
    return !isDarkMode(context)
        ? AppTheme.lightScheme().primaryContainer
        : AppTheme.darkScheme().surfaceContainerHigh;
  }

  static Color cardBackgroundColor(BuildContext context) {
    return isDarkMode(context)
        ? AppTheme.darkScheme().surfaceContainerHigh
        : AppTheme.lightScheme().surfaceContainer;
  }
}

// A MD3 ColorScheme helper for MD3 App Theme
class MaterialScheme {
  const MaterialScheme({
    required this.brightness,
    required this.primary,
    required this.surfaceTint,
    required this.onPrimary,
    required this.primaryContainer,
    required this.onPrimaryContainer,
    required this.secondary,
    required this.onSecondary,
    required this.secondaryContainer,
    required this.onSecondaryContainer,
    required this.tertiary,
    required this.onTertiary,
    required this.tertiaryContainer,
    required this.onTertiaryContainer,
    required this.error,
    required this.onError,
    required this.errorContainer,
    required this.onErrorContainer,
    required this.background,
    required this.onBackground,
    required this.surface,
    required this.onSurface,
    required this.surfaceVariant,
    required this.onSurfaceVariant,
    required this.outline,
    required this.outlineVariant,
    required this.shadow,
    required this.scrim,
    required this.inverseSurface,
    required this.inverseOnSurface,
    required this.inversePrimary,
    required this.primaryFixed,
    required this.onPrimaryFixed,
    required this.primaryFixedDim,
    required this.onPrimaryFixedVariant,
    required this.secondaryFixed,
    required this.onSecondaryFixed,
    required this.secondaryFixedDim,
    required this.onSecondaryFixedVariant,
    required this.tertiaryFixed,
    required this.onTertiaryFixed,
    required this.tertiaryFixedDim,
    required this.onTertiaryFixedVariant,
    required this.surfaceDim,
    required this.surfaceBright,
    required this.surfaceContainerLowest,
    required this.surfaceContainerLow,
    required this.surfaceContainer,
    required this.surfaceContainerHigh,
    required this.surfaceContainerHighest,
  });

  final Brightness brightness;
  final Color primary;
  final Color surfaceTint;
  final Color onPrimary;
  final Color primaryContainer;
  final Color onPrimaryContainer;
  final Color secondary;
  final Color onSecondary;
  final Color secondaryContainer;
  final Color onSecondaryContainer;
  final Color tertiary;
  final Color onTertiary;
  final Color tertiaryContainer;
  final Color onTertiaryContainer;
  final Color error;
  final Color onError;
  final Color errorContainer;
  final Color onErrorContainer;
  final Color background;
  final Color onBackground;
  final Color surface;
  final Color onSurface;
  final Color surfaceVariant;
  final Color onSurfaceVariant;
  final Color outline;
  final Color outlineVariant;
  final Color shadow;
  final Color scrim;
  final Color inverseSurface;
  final Color inverseOnSurface;
  final Color inversePrimary;
  final Color primaryFixed;
  final Color onPrimaryFixed;
  final Color primaryFixedDim;
  final Color onPrimaryFixedVariant;
  final Color secondaryFixed;
  final Color onSecondaryFixed;
  final Color secondaryFixedDim;
  final Color onSecondaryFixedVariant;
  final Color tertiaryFixed;
  final Color onTertiaryFixed;
  final Color tertiaryFixedDim;
  final Color onTertiaryFixedVariant;
  final Color surfaceDim;
  final Color surfaceBright;
  final Color surfaceContainerLowest;
  final Color surfaceContainerLow;
  final Color surfaceContainer;
  final Color surfaceContainerHigh;
  final Color surfaceContainerHighest;
}

extension MaterialSchemeUtils on MaterialScheme {
  ColorScheme toColorScheme() {
    return ColorScheme(
      brightness: brightness,
      primary: primary,
      onPrimary: onPrimary,
      primaryContainer: primaryContainer,
      onPrimaryContainer: onPrimaryContainer,
      secondary: secondary,
      onSecondary: onSecondary,
      secondaryContainer: secondaryContainer,
      onSecondaryContainer: onSecondaryContainer,
      tertiary: tertiary,
      onTertiary: onTertiary,
      tertiaryContainer: tertiaryContainer,
      onTertiaryContainer: onTertiaryContainer,
      error: error,
      onError: onError,
      errorContainer: errorContainer,
      onErrorContainer: onErrorContainer,
      background: background,
      onBackground: onBackground,
      surface: surface,
      onSurface: onSurface,
      surfaceVariant: surfaceVariant,
      onSurfaceVariant: onSurfaceVariant,
      outline: outline,
      outlineVariant: outlineVariant,
      shadow: shadow,
      scrim: scrim,
      inverseSurface: inverseSurface,
      onInverseSurface: inverseOnSurface,
      inversePrimary: inversePrimary,
    );
  }
}
